crops_and_markets/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	# administrator
	url(r'^admin/', include(admin.site.urls)),

	# general views
	url(r'^$', 'crops_and_markets_app.views.login', name='login'),
	url(r'^about', 'crops_and_markets_app.views.about', name='about'),
	url(r'^access_denied', 'crops_and_markets_app.views.access_denied', name='access_denied'),
	url(r'^accounts/login', 'crops_and_markets_app.views.access_denied', name='access_denied'),
	url(r'^export_documents', 'crops_and_markets_app.views.export_documents', name='export_documents'),
	url(r'^index', 'crops_and_markets_app.views.home', name='home'),
	url(r'^home', 'crops_and_markets_app.views.home', name='home'),
	url(r'^logout', 'crops_and_markets_app.views.logout', name='logout'),

	# crops
	url(r'^add_crop', 'crops_and_markets_app.views.add_crop', name='add_crop'),
	url(r'^add_plantation', 'crops_and_markets_app.views.add_plantation', name='add_plantation'),
	url(r'^crop_info', 'crops_and_markets_app.views.crop_info', name='crop_info'),
	url(r'^crop_map', 'crops_and_markets_app.views.crop_map', name='crop_map'),
	url(r'^crop_table', 'crops_and_markets_app.views.crop_table', name='crop_table'),
	url(r'^crops$', 'crops_and_markets_app.views.crops', name='crops'),
	url(r'^export_crops_xlsx', 'crops_and_markets_app.views.export_crops_xlsx', name='export_crops_xlsx'),
	url(r'^photo_library', 'crops_and_markets_app.views.photo_library', name='photo_library'),
	url(r'^plantation_info', 'crops_and_markets_app.views.plantation_info', name='plantation_info'),
	url(r'^plantation_table', 'crops_and_markets_app.views.plantation_table', name='plantation_table'),

	# markets
	url(r'^add_market', 'crops_and_markets_app.views.add_market', name='add_market'),
	url(r'^add_sale', 'crops_and_markets_app.views.add_sale', name='add_sale'),
	url(r'^export_markets_xlsx', 'crops_and_markets_app.views.export_markets_xlsx', name='export_markets_xlsx'),
	url(r'^market_company', 'crops_and_markets_app.views.market_company', name='market_company'),
	url(r'^market_info', 'crops_and_markets_app.views.market_info', name='market_info'),
	url(r'^market_map', 'crops_and_markets_app.views.market_map', name='market_map'),
	url(r'^market_table$', 'crops_and_markets_app.views.market_table', name='market_table'),
	url(r'^market_table_potential', 'crops_and_markets_app.views.market_table_potential', name='market_table_potential'),
	url(r'^markets$', 'crops_and_markets_app.views.markets', name='markets'),
	url(r'^sales_detail', 'crops_and_markets_app.views.sales_detail', name='sales_detail'),
	url(r'^sales_history', 'crops_and_markets_app.views.sales_history', name='sales_history'),

	# related
	url(r'^add_related', 'crops_and_markets_app.views.add_related', name='add_related'), 
	url(r'^related$', 'crops_and_markets_app.views.related', name='related'),
	url(r'^related_info', 'crops_and_markets_app.views.related_info', name='related_info'),
	url(r'^related_table', 'crops_and_markets_app.views.related_table', name='related_table')
)


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crops_and_markets_app/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import smart_text

# ######## #
# General
class Region(models.Model):
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name.encode('utf-8')

class Province(models.Model):
	name = models.CharField(max_length=100)
	region = models.ForeignKey('Region')
	def __str__(self):
		return self.name.encode('utf-8')

class Commune(models.Model):
	name = models.CharField(max_length=100)
	province = models.ForeignKey('Province')
	def __str__(self):
		return self.name.encode('utf-8')


class PotatoVariety(models.Model):
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name.encode('utf-8')

class Certification(models.Model):
	certification = models.CharField(max_length=20)
	def __str__(self):
		return self.certification.encode('utf-8')
		

# ######## #
# Crops	
class CompanyCrop(models.Model):
	name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)

	def __str__(self):
		return self.name.encode('utf-8')


class Crop(models.Model):
	name = models.CharField(max_length=256)
	timestamp = models.DateTimeField(auto_now_add=True)
	crop_owner = models.ManyToManyField('CropOwner')

	# geographical information
	region = models.ForeignKey('Region', blank=True, null=True)
	province = models.ForeignKey('Province', blank=True, null=True)
	commune = models.ForeignKey('Commune', blank=True, null=True)
	address = models.CharField(max_length=256, blank=True, null=True)
 	latitude = models.FloatField(blank=True, null=True)
 	longitude = models.FloatField(blank=True, null=True)
 	
	# general characterisitcs
	has = models.FloatField(blank=True, null=True) #PositiveSmallIntegerField(blank=True, null=True)

	# terrain characteristics 
	# core characteristics -- as boolean and then text for observation/comments
	water = models.BooleanField()
	soil = models.BooleanField()
	topography = models.BooleanField()
	temperatures = models.BooleanField()
	access = models.BooleanField()

	# core characteristics comments
	water_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	soil_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	topography_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	temperatures_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	access_cmnt = models.CharField(max_length=1024, blank=True, null=True)

	# secondary characteristics
	observations = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.name.encode('utf-8')


class CropImage(models.Model):
	crop = models.ForeignKey('Crop')
	timestamp = models.DateTimeField(auto_now_add=True)
	image = models.ImageField(max_length=255, upload_to='crop-media/')


class CropOwner(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	# crop -- there is a ManyToMany field relating crops with owners.
	# crop_owner.crop_set.all() -- this should give all the crops for this owner.
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)
	contact_number_1 = models.CharField(max_length=16, blank=True, null=True)
	contact_number_2 = models.CharField(max_length=16, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	position = models.CharField(max_length=100, blank=True, null=True)

	company = models.ForeignKey('CompanyCrop', null=True)

	def __str__(self):
		return self.first_name.encode('utf-8') + " " + self.last_name.encode('utf-8')


class Plantation(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	date = date = models.DateField()
	crop = models.ForeignKey('Crop')
	paddock = models.CharField(max_length=80)
	variety = models.ForeignKey('PotatoVariety')
	source_lot = models.CharField(max_length=16)
	kg_seeds = models.FloatField()
	kg_fert = models.FloatField(blank=True, null=True)
	n_mini = models.FloatField(blank=True, null=True)
	has = models.FloatField()
	control_number = models.CharField(max_length=16, unique=True)
	obs = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.control_number.encode('utf-8')


# ######## #
# Markets
class Client(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	type_of_client = models.ForeignKey('TypeOfClient')

	# contact information
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)
	contact_number_1 = models.CharField(max_length=16, blank=True, null=True)
	contact_number_2 = models.CharField(max_length=16, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	position = models.CharField(max_length=100, blank=True, null=True)
	observations = models.TextField(blank=True, null=True)

	# company information
	company = models.ForeignKey('CompanyMarket', null=True)

	def __str__(self):
		return self.first_name.encode('utf-8') + " " + self.last_name.encode('utf-8')


class CompanyMarket(models.Model):
	name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)

	def __str__(self):
		return self.name.encode('utf-8')


class GeoMarker(models.Model):
	client = models.ForeignKey('Client')
	region = models.ForeignKey('Region', blank=True, null=True)
	province = models.ForeignKey('Province', blank=True, null=True)
	commune = models.ForeignKey('Commune', blank=True, null=True)
	address = models.CharField(max_length=256, blank=True, null=True)

	def __str__(self):
		if self.address is not None:
			return str(self.client) + ": " + str(self.address)
		else:
			return str(self.client)

	def get_address(self):
		address = ""
		if self.address is not None:
			address = address + self.address
			if self.region is not None:
				adress = address + ", " + self.region
			address = address + ", Chile"
		return address


class Sale(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User)
	client = models.ForeignKey('Client')
	type_of_transaction = models.ForeignKey('TypeOfTransaction')
	date = models.DateField()
	observations = models.TextField(blank=True, null=True)

	def get_volume(self):
		total_volume = 0
		for detail in self.saledetail_set.all():
			total_volume += detail.volume
		return total_volume

	def get_price(self):
		total_price = 0
		for detail in self.saledetail_set.all():
			total_price += detail.price
		return total_price

	# return string with varieties separated by char ' '
	def get_varieties(self):
		varieties = ""
		for detail in self.saledetail_set.all():
			varieties += ' ' + str(detail.variety)
		return varieties


class SaleDetail(models.Model):
	sale = models.ForeignKey('Sale')
	volume = models.IntegerField()
	price = models.IntegerField()
	variety = models.ForeignKey('PotatoVariety')
	certificate = models.ForeignKey('Certification')


class TypeOfClient(models.Model):
	type = models.CharField(max_length=8)

	def __str__(self):
		return self.type


class TypeOfTransaction(models.Model):
	type = models.CharField(max_length=8)

	def __str__(self):
		return self.type


# ######## #
# Related
class Related(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)
	contact_number_1 = models.CharField(max_length=16, blank=True, null=True)
	contact_number_2 = models.CharField(max_length=16, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	observations = models.TextField(blank=True, null=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	area = models.ForeignKey('RelatedArea')

	def __str__(self):
		return self.first_name.encode('utf-8') + " " + self.last_name.encode('utf-8')


class RelatedArea(models.Model):
	area = models.CharField(max_length=100)

	def __str__(self):
		return self.area.encode('utf-8')

crops_and_markets_app/templates/crops/add_owner.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="crops and markets, and bkupfer's thesis">
	<meta name="keywords" content="semillas sz, crops and markerts, bkupfer">
	<meta name="author" content="bkupfer">
	<link rel="shortcut icon" href="static/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="static/img/favicon.ico" type="image/x-icon">

	<title>Crops and Markets</title>

	<!-- Bootstrap Core CSS -->
	<link href="static/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom CSS -->
	<link href="static/css/simple-sidebar.css" rel="stylesheet">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div id="wrapper">

		{% include "sidebar.html" %}

		<div id="page-content-wrapper">
			<div class="container-fluid">

				<h2>Agregar un nuevo propietario</h2>

				<!-- For message to user -->
				{% if messages %}
				<div class="row">
					<div class="col-sm-12">
					{% for message in messages %}
						<p class="alert alert-{% if message.tags == "success" %}success{% else %}danger{% endif %} text-center">
							{{ message }}
						</p>
					{% endfor %}
					</div>
				</div> 
				{% endif %}

				<div class="panel-body">
					<!-- Add new client form -->
					<form action="" method="POST"> {% csrf_token %}

						<!-- Contact information -->
						<div class="row">
							<h3>Información de contacto</h3>
							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="first_name">Nombre <label style="color:red">*</label></label>
								<div class="col-sm-8">
									{{ owner_form.first_name }}
								</div>
							</div>
							{{ owner_form.first_name.errors }}
							
							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="last_name">Apellido <label style="color:red">*</label></label>
								<div class="col-sm-8">
									{{ owner_form.last_name }}
								</div>
							</div>
							{{ owner_form.last_name.errors }}

							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="contact_number_1">Número de contacto</label>
								<div class="col-sm-8">
									{{ owner_form.contact_number_1 }}
								</div>
							</div>
							{{ owner_form.contact_numbers_1.errors }}
						
							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="contact_number_2">Número de contacto 2</label>
								<div class="col-sm-8">
									{{ owner_form.contact_number_2 }}
								</div>
							</div>
							{{ owner_form.contact_numbers_2.errors }}

							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="email">Email</label>
								<div class="col-sm-8">
									{{ owner_form.email }}
								</div>
							</div>
							{{ owner_form.email.errors }}

							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="cargo">Cargo</label>
								<div class="col-sm-8">
									{{ owner_form.charge }}
								</div>
							</div>
							{{ owner_form.email.charge }}
						</div>

						<!-- Company information -->
						<div class="row">
							<h3>Información de compañía</h3>
							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="observations">Compañía</label>
								<div class="col-sm-8">
									{{ company_form.excisting_company }}
								</div>
							</div>

							<div class="col-sm-12"><br>
								<label class="control-label col-sm-4" for="observations">Nombre compañía</label>
								<div class="col-sm-8">
									{{ company_form.name }}
								</div>
								{{ company_form.name.errors }}
							</div>

							<div class="col-sm-12">
								<label class="control-label col-sm-4" for="observations">Rut compañía</label>
								<div class="col-sm-8">
									{{ company_form.rut }}
								</div>
								{{ company_form.rut.errors }}
							</div>
						</div>

						<!-- Observations -->
						<div class="row">
							<h3>Observaciones</h3>
							<div class="col-sm-12">
								{{ owner_form.observations }}
							</div>
							{{ owner_form.observations.errors }}
						</div>

						<br>
						<!-- Submit button -->
						<div class="row">
							<div class="col-sm-4">
								<input type="submit" value="Agregar" class="btn btn-default">
							</div>
							<div class="col-sm-8">
								<p class="text-right">Los campos marcados como (<label style="color:red">*</label>) son obligatorios.</p>
							</div>
						</div>

					</form>
					<hr><a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Alternar Menu</a>
				</div>

			</div>
		</div>
	</div>

	<script src="static/js/jquery.js"></script>
	<script src="static/js/bootstrap.min.js"></script>
	<script src="static/js/menu_toggle.js"></script>
	<script src="static/js/googleanalytics.js"></script>
	
</body>

</html>

crops_and_markets_app/templates/crops/crop_table.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="crops and markets, and bkupfer's thesis">
	<meta name="keywords" content="semillas sz, crops and markerts, bkupfer">
	<meta name="author" content="bkupfer">
	<link rel="shortcut icon" href="static/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="static/img/favicon.ico" type="image/x-icon">

	<title>Crops and Markets</title>

	<!-- Bootstrap Core CSS -->
	<link href="static/css/bootstrap.min.css" rel="stylesheet">
	<link href="static/css/simple-sidebar.css" rel="stylesheet">

	<style type="text/css">
		input {
			border:solid 1px #ccc;
			border-radius: 5px;
			padding:7px 14px;
			margin-bottom:10px
		}
		input:focus {
			border-color:#aaa;
		}
	</style>
	
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">

	<script src="static/js/jquery.js"></script>
	<script async src="static/js/bootstrap.min.js"></script>
	<script async src="static/js/menu_toggle.js"></script>
	<script defer src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
	<script async src="static/js/googleanalytics.js"></script>


	<!--<link href="static/css/jquery.dataTables.min.css" rel="stylesheet">
		<script src="static/js/jquery.dataTables.min.js"></script>
	-->
	
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

	<script>
	$(document).ready(function(){
		$('#crops-table').DataTable({
			 "language": {
			 	"url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
			}
		});
	});
	</script>

</head>

<body>

	<div id="wrapper">

		{% include "sidebar.html" %}

		<div id="page-content-wrapper">
			<div class="container-fluid">

				<h2>Tabla de predios</h2>

				{% if messages %}
				<!-- For message to user -->
				<div class="row">
					<div class="col-sm-12">
					{% for message in messages %}
						<p class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %} text-center">
							{{ message }}
						</p>
					{% endfor %}
					</div>
				</div> 
				{% endif %}

				<!-- <h3>Información de contacto</h3> -->

				<table id="crops-table" class="display" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>Predio</th>
							<th>Propietario</th>
							<th>Región</th>
							<th>Provincia</th>
							<th style="text-align: center;">Puntuación</th>
						</tr>
					</thead>
					<tbody class="list">
						{% for crop in crops %}
						<tr>
							<td><a href="crop_info?id={{ crop.pk }}">{{ crop.name }}</a></td>
							<td>
								{% for owner in crop.crop_owner.all %}
									{{ owner }}
								{% endfor %}
							</td>
							<td>{{ crop.region }}</td>
							<td>{% if crop.province %}{{ crop.province }}{% else %}No hay info{% endif %}</td>
							<td style="text-align: center;">
								<span class="glyphicon glyphicon-star" aria-hidden="true" style="color: black;"></span>
								{% if crop.score > 20 %}
									<span class="glyphicon glyphicon-star" aria-hidden="true" style="color: black;"></span>
									{% if crop.score > 40 %}
										<span class="glyphicon glyphicon-star" aria-hidden="true" style="color: black;"></span>
										{% if crop.score > 60 %}
											<span class="glyphicon glyphicon-star" aria-hidden="true" style="color: black;"></span>
											{% if crop.score > 80 %}
												<span class="glyphicon glyphicon-star" aria-hidden="true" style="color: black;"></span>
											{% endif %}
										{% endif %}
									{% endif %}
								{% endif %}
							</td>
						</tr>
						{% empty %}
						<tr>
							<td>No hay predios en la base de datos.</td>
							<td></td><td></td><td></td><td></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				<hr>{% include "menu_toggle.html" %}
			</div>
		</div>
	</div>

</body>

<script>
	$("#crops_table").addClass("active");
</script>

</html>

crops_and_markets_app/templates/crops/plantation_info.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="crops and markets, and bkupfer's thesis">
	<meta name="keywords" content="semillas sz, crops and markerts, bkupfer">
	<meta name="author" content="bkupfer">
	<link rel="shortcut icon" href="static/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="static/img/favicon.ico" type="image/x-icon">

	<title>Crops and Markets</title>

	<!-- Bootstrap Core CSS -->
	<link href="static/css/bootstrap.min.css" rel="stylesheet">
	<link href="static/css/simple-sidebar.css" rel="stylesheet">

	<style>
	#map-canvas {
		width: 100%;
		height: 250px;
		border-style: solid;
	}

	.write {
		display: none;
	}
	</style>

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

	<script src="https://maps.googleapis.com/maps/api/js?sensor=true&v=3"></script>
	<script src="static/js/jquery.js"></script>
	<script async src="static/js/bootstrap.min.js"></script>
	<script async src="static/js/menu_toggle.js"></script>
	<script async src="static/js/googleanalytics.js"></script>
	<script async src="static/js/regions.js"></script>

</head>

<body>

	<div id="wrapper">

		{% include "sidebar.html" %}

		<!-- Page Content -->
		<div id="page-content-wrapper">
			<div class="container-fluid">
				<div class="row">
					<h2>Detalle plantación
						<button id="edit-button" class="btn btn-success pull-right">Editar</button>
						<button type="submit" form="edit-form" class="btn btn-primary pull-right save-changes" style="display: none;">Guardar</button>
					</h2>

					{% if messages %}
					<!-- For message to user -->
					<div class="row">
						<div class="col-xs-12">
						{% for message in messages %}
							<p class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %} text-center">
								{{ message }}
							</p>
						{% endfor %}
						</div>
					</div> 
					{% endif %}
				
					<form action="plantation_info?cn={{ plantation.control_number }}" method="POST" id="edit-form">{%csrf_token %}
						<!-- Contact information -->
						<h3>Plantación n° {{ plantation.control_number }}</h3>
						<table class="table table-hover">
							<tr>
								<td class="col-xs-4">Fecha</td>
								<td class="col-xs-8">{{ plantation.date }}</td>
								<!-- <td class="write">{{ plantation_form.date }}</td>  -->
							</tr>
							<tr>
								<td>Predio</td>
								<td class="read">{{ plantation.crop }}</td>
								<td class="write">{{ plantation_form.crop }}</td>
							</tr>
							<tr>
								<td>Potrero</td>
								<td class="read">{{ plantation.paddock }}</a></td>
								<td class="write">{{ plantation_form.paddock }}</td>
							</tr>
							<tr>
								<td>Variedad</td>
								<td class="read">{{ plantation.variety }}</td>
								<td class="write">{{ plantation_form.variety }}</td>
							</tr>
							<tr>
								<td>Lote origen</td>
								<td class="read">{{ plantation.source_lot }}</td>
								<td class="write">{{ plantation_form.source_lot }}</td>
							</tr>
							<tr>
								<td>Kg. semillas</td>
								<td class="read">{{ plantation.kg_seeds }}</td>
								<td class="write">{{ plantation_form.kg_seeds }}</td>
							</tr>
							<tr>
								<td>Kg. fertilizante</td>
								<td class="read">{{ plantation.kg_fert }}</td>
								<td class="write">{{ plantation_form.kg_fert }}</td>
							</tr>
							<tr>
								<td>N mini</td>
								<td class="read">{{ plantation.n_mini }}</td>
								<td class="write">{{ plantation_form.n_mini }}</td>
							</tr>
							<tr>
								<td>Has</td>
								<td class="read">{{ plantation.has }}</td>
								<td class="write">{{ plantation_form.has }}</td>
							</tr>
							<tr>
								<td>N° Control Final SAG</td>
								<td>{{ plantation.control_number }}</td>
								<span style="display: none;">{{ plantation_form.control_number }}</span>
							</tr>
						</table>
						
						<h3>Observaciones</h3>
						<div class="read" style="border: 1px solid #CCCCCC">
							<p id="observations" class="text-justify" style="margin: 1%; white-space: pre-wrap">{{ plantation.obs }}</p>
						</div>
						<div class="write" style="display: none;">
							{{ plantation_form.obs }}
						</div>

						<br class="write">
						<button type="submit" form="edit-form" class="btn btn-primary save-changes" style="display: none;">Guardar</button>
						<button name="delete" class="btn btn-danger pull-right write" style="display: none;" onclick="return confirm('Está seguro que desea eliminar la plantación con número de control; {{ plantation.control_number }}, de la base de datos?\nEste proceso es irreversible.');">Borrar</button>
					</form>

					<hr>{% include "menu_toggle.html" %}
					<a href="plantation_table" class="btn btn-default" id="return">Volver</a>
				</div>
			</div>
		</div>

	</div>

	<script type="text/javascript">
	$(document).ready(function(){
		//$("#id_date").val("{{ plantation.date }}");
		$("#id_crop")[0].selectedIndex = {{ plantation.crop.pk }};
		$("#id_paddock").val("{{ plantation.paddock }}");
		$("#id_variety")[0].selectedIndex = {{ plantation.variety.pk }};
		$("#id_source_lot").val("{{ plantation.source_lot }}");
		$("#id_kg_seeds").val("{{ plantation.kg_seeds }}");
		$("#id_n_mini").val({{ plantation.n_mini }});
		$("#id_has").val({{ plantation.has }});
		$("#id_control_number").val("{{ plantation.control_number }}");
		$("#id_obs").val( $("#observations").text() );
	});

	$("#edit-button").click(function (){
		$(".save-changes").slideToggle("fast");
		$(".read").toggle();
		$("#number-2").show();
		$(".write").toggle(100);
	});
	</script>

</body>

</html>