crops_and_markets/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	# administrator
	url(r'^admin/', include(admin.site.urls)),

	# general views
	url(r'^$', 'crops_and_markets_app.views.login', name='login'),
	url(r'^about', 'crops_and_markets_app.views.about', name='about'),
	url(r'^access_denied', 'crops_and_markets_app.views.access_denied', name='access_denied'),
	url(r'^accounts/login', 'crops_and_markets_app.views.access_denied', name='access_denied'),
	url(r'^export_documents', 'crops_and_markets_app.views.export_documents', name='export_documents'),
	url(r'^index', 'crops_and_markets_app.views.home', name='home'),
	url(r'^home', 'crops_and_markets_app.views.home', name='home'),
	url(r'^logout', 'crops_and_markets_app.views.logout', name='logout'),

	# crops
	url(r'^add_crop', 'crops_and_markets_app.views.add_crop', name='add_crop'),
	url(r'^add_plantation', 'crops_and_markets_app.views.add_plantation', name='add_plantation'),
	url(r'^crop_info', 'crops_and_markets_app.views.crop_info', name='crop_info'),
	url(r'^crop_map', 'crops_and_markets_app.views.crop_map', name='crop_map'),
	url(r'^crop_table', 'crops_and_markets_app.views.crop_table', name='crop_table'),
	url(r'^crops$', 'crops_and_markets_app.views.crops', name='crops'),
	url(r'^export_crops_xlsx', 'crops_and_markets_app.views.export_crops_xlsx', name='export_crops_xlsx'),
	url(r'^photo_library', 'crops_and_markets_app.views.photo_library', name='photo_library'),
	url(r'^plantation_info', 'crops_and_markets_app.views.plantation_info', name='plantation_info'),
	url(r'^plantation_table', 'crops_and_markets_app.views.plantation_table', name='plantation_table'),

	# markets
	url(r'^add_market', 'crops_and_markets_app.views.add_market', name='add_market'),
	url(r'^add_sale', 'crops_and_markets_app.views.add_sale', name='add_sale'),
	url(r'^export_markets_xlsx', 'crops_and_markets_app.views.export_markets_xlsx', name='export_markets_xlsx'),
	url(r'^market_company', 'crops_and_markets_app.views.market_company', name='market_company'),
	url(r'^market_info', 'crops_and_markets_app.views.market_info', name='market_info'),
	url(r'^market_map', 'crops_and_markets_app.views.market_map', name='market_map'),
	url(r'^market_table$', 'crops_and_markets_app.views.market_table', name='market_table'),
	url(r'^market_table_potential', 'crops_and_markets_app.views.market_table_potential', name='market_table_potential'),
	url(r'^markets$', 'crops_and_markets_app.views.markets', name='markets'),
	url(r'^sales_detail', 'crops_and_markets_app.views.sales_detail', name='sales_detail'),
	url(r'^sales_history', 'crops_and_markets_app.views.sales_history', name='sales_history'),

	# related
	url(r'^add_related', 'crops_and_markets_app.views.add_related', name='add_related'), 
	url(r'^related$', 'crops_and_markets_app.views.related', name='related'),
	url(r'^related_info', 'crops_and_markets_app.views.related_info', name='related_info'),
	url(r'^related_table', 'crops_and_markets_app.views.related_table', name='related_table')
)


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crops_and_markets_app/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import smart_text

# ######## #
# General
class Region(models.Model):
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name.encode('utf-8')

class Province(models.Model):
	name = models.CharField(max_length=100)
	region = models.ForeignKey('Region')
	def __str__(self):
		return self.name.encode('utf-8')

class Commune(models.Model):
	name = models.CharField(max_length=100)
	province = models.ForeignKey('Province')
	def __str__(self):
		return self.name.encode('utf-8')


class PotatoVariety(models.Model):
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name.encode('utf-8')

class Certification(models.Model):
	certification = models.CharField(max_length=20)
	def __str__(self):
		return self.certification.encode('utf-8')
		

# ######## #
# Crops	
class CompanyCrop(models.Model):
	name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)

	def __str__(self):
		return self.name.encode('utf-8')


class Crop(models.Model):
	name = models.CharField(max_length=256)
	timestamp = models.DateTimeField(auto_now_add=True)
	crop_owner = models.ManyToManyField('CropOwner')

	# geographical information
	region = models.ForeignKey('Region', blank=True, null=True)
	province = models.ForeignKey('Province', blank=True, null=True)
	commune = models.ForeignKey('Commune', blank=True, null=True)
	address = models.CharField(max_length=256, blank=True, null=True)
 	latitude = models.FloatField(blank=True, null=True)
 	longitude = models.FloatField(blank=True, null=True)
 	
	# general characterisitcs
	has = models.FloatField(blank=True, null=True) #PositiveSmallIntegerField(blank=True, null=True)

	# terrain characteristics 
	# core characteristics -- as boolean and then text for observation/comments
	water = models.BooleanField()
	soil = models.BooleanField()
	topography = models.BooleanField()
	temperatures = models.BooleanField()
	access = models.BooleanField()

	# core characteristics comments
	water_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	soil_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	topography_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	temperatures_cmnt = models.CharField(max_length=1024, blank=True, null=True)
	access_cmnt = models.CharField(max_length=1024, blank=True, null=True)

	# secondary characteristics
	observations = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.name.encode('utf-8')


class CropImage(models.Model):
	crop = models.ForeignKey('Crop')
	timestamp = models.DateTimeField(auto_now_add=True)
	image = models.ImageField(max_length=255, upload_to='crop-media/')


class CropOwner(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	# crop -- there is a ManyToMany field relating crops with owners.
	# crop_owner.crop_set.all() -- this should give all the crops for this owner.
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)
	contact_number_1 = models.CharField(max_length=16, blank=True, null=True)
	contact_number_2 = models.CharField(max_length=16, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	position = models.CharField(max_length=100, blank=True, null=True)

	company = models.ForeignKey('CompanyCrop', null=True)

	def __str__(self):
		return self.first_name.encode('utf-8') + " " + self.last_name.encode('utf-8')


class Plantation(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	date = date = models.DateField()
	crop = models.ForeignKey('Crop')
	paddock = models.CharField(max_length=80)
	variety = models.ForeignKey('PotatoVariety')
	source_lot = models.CharField(max_length=16)
	kg_seeds = models.FloatField()
	kg_fert = models.FloatField(blank=True, null=True)
	n_mini = models.FloatField(blank=True, null=True)
	has = models.FloatField()
	control_number = models.CharField(max_length=16, unique=True)
	obs = models.TextField(blank=True, null=True)

	def __str__(self):
		return self.control_number.encode('utf-8')


# ######## #
# Markets
class Client(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	type_of_client = models.ForeignKey('TypeOfClient')

	# contact information
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)
	contact_number_1 = models.CharField(max_length=16, blank=True, null=True)
	contact_number_2 = models.CharField(max_length=16, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	position = models.CharField(max_length=100, blank=True, null=True)
	observations = models.TextField(blank=True, null=True)

	# company information
	company = models.ForeignKey('CompanyMarket', null=True)

	def __str__(self):
		return self.first_name.encode('utf-8') + " " + self.last_name.encode('utf-8')


class CompanyMarket(models.Model):
	name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)

	def __str__(self):
		return self.name.encode('utf-8')


class GeoMarker(models.Model):
	client = models.ForeignKey('Client')
	region = models.ForeignKey('Region', blank=True, null=True)
	province = models.ForeignKey('Province', blank=True, null=True)
	commune = models.ForeignKey('Commune', blank=True, null=True)
	address = models.CharField(max_length=256, blank=True, null=True)

	def __str__(self):
		if self.address is not None:
			return str(self.client) + ": " + str(self.address)
		else:
			return str(self.client)

	def get_address(self):
		address = ""
		if self.address is not None:
			address = address + self.address
			if self.region is not None:
				adress = address + ", " + self.region
			address = address + ", Chile"
		return address


class Sale(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User)
	client = models.ForeignKey('Client')
	type_of_transaction = models.ForeignKey('TypeOfTransaction')
	date = models.DateField()
	observations = models.TextField(blank=True, null=True)

	def get_volume(self):
		total_volume = 0
		for detail in self.saledetail_set.all():
			total_volume += detail.volume
		return total_volume

	def get_price(self):
		total_price = 0
		for detail in self.saledetail_set.all():
			total_price += detail.price
		return total_price

	# return string with varieties separated by char ' '
	def get_varieties(self):
		varieties = ""
		for detail in self.saledetail_set.all():
			varieties += ' ' + str(detail.variety)
		return varieties


class SaleDetail(models.Model):
	sale = models.ForeignKey('Sale')
	volume = models.IntegerField()
	price = models.IntegerField()
	variety = models.ForeignKey('PotatoVariety')
	certificate = models.ForeignKey('Certification')


class TypeOfClient(models.Model):
	type = models.CharField(max_length=8)

	def __str__(self):
		return self.type


class TypeOfTransaction(models.Model):
	type = models.CharField(max_length=8)

	def __str__(self):
		return self.type


# ######## #
# Related
class Related(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	rut = models.CharField(max_length=20, blank=True, null=True)
	contact_number_1 = models.CharField(max_length=16, blank=True, null=True)
	contact_number_2 = models.CharField(max_length=16, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	observations = models.TextField(blank=True, null=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	area = models.ForeignKey('RelatedArea')

	def __str__(self):
		return self.first_name.encode('utf-8') + " " + self.last_name.encode('utf-8')


class RelatedArea(models.Model):
	area = models.CharField(max_length=100)

	def __str__(self):
		return self.area.encode('utf-8')

crops_and_markets_app/templates/markets/market_info.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="crops and markets, and bkupfer's thesis">
	<meta name="keywords" content="semillas sz, crops and markerts, bkupfer">
	<meta name="author" content="bkupfer">
	<link rel="shortcut icon" href="static/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="static/img/favicon.ico" type="image/x-icon">

	<title>Crops and Markets</title>

	<!-- Bootstrap Core CSS -->
	<link href="static/css/bootstrap.min.css" rel="stylesheet">
	<link href="static/css/simple-sidebar.css" rel="stylesheet">

	<style>
	#map-canvas {
		width: 100%;
		height: 250px;
		border-style: solid;
	}
	.write {
		display: none;
	}
	</style>
	
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

	<!-- Google maps -->
	<script src="https://maps.googleapis.com/maps/api/js"></script>
	<script src="static/js/jquery.js"></script>
	<script async src="static/js/bootstrap.min.js"></script>
	<script async src="static/js/googleanalytics.js"></script>
	<script async src="static/js/menu_toggle.js"></script>
	<script async src="static/js/regions.js"></script>
	<script async src="static/js/rut_validator.js"></script>

	<script>
	/** shows or hides map */
	var map_init = false;
	function displayMap(){
		var button = $("#mapButton");
		button.text(button.text() == "Mostrar mapa" ? "Ocultar mapa" : "Mostrar mapa");

		var mapCanvas = $("#map-canvas");
		mapCanvas.slideToggle("slow");

		if (! map_init) {
			initialize();
			map_init = true;
		}
	}

	/* initializes the map and places marker */
	function initialize(){
		var address = "{{ geo_info.address }}, {{ geo_info.region }}, Chile";
		var mapCanvas = $("#map-canvas")[0];
		if (address != ""){
			var mapOptions = {
				zoom: 10,
				mapTypeId: google.maps.MapTypeId.ROADMAP
			};

			var geocoder = new google.maps.Geocoder();
			geocoder.geocode({'address': address}, function(results, status){
				if (status == google.maps.GeocoderStatus.OK){
					mapOptions.center = results[0].geometry.location;
					var map = new google.maps.Map(mapCanvas, mapOptions);

					var marker = new google.maps.Marker({
						position: results[0].geometry.location, 
						map: map
					});

					var typeOfClient = "{{ client.type_of_client }}";
					if (typeOfClient == "Actual")
							marker.setIcon('http://maps.google.com/mapfiles/ms/icons/green-dot.png');
					if (typeOfClient == "Potencial")
							marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png');
					
					var infoWindow = new google.maps.InfoWindow({
						content: "{{ client }}"
					});
					google.maps.event.addListener(marker, 'click', function(){
						infoWindow.open(map, marker);
					}); 
				}
				else {
					alert('Geocode was not succesful for the following reason:' + status); 
				}
			});
		}
		else mapCanvas.text("No se tiene información geográfica respecto de este cliente.");
	}
	</script>

</head>

<body>

	<div id="wrapper">

		{% include "sidebar.html" %}

		<div id="page-content-wrapper">
			<div class="container-fluid">
				<div class="row">
					<h2>Detalle {{ client }}
						<button id="edit-button" class="btn btn-success pull-right">Editar</button>
						<button type="submit" form="edit-form" class="btn btn-primary pull-right save-changes" style="display: none;">Guardar</button>
					</h2>

					{% if messages %}
					<!-- For message to user -->
					<div class="row">
						<div class="col-xs-12">
						{% for message in messages %}
							<p class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %} text-center">
								{{ message }}
							</p>
						{% endfor %}
						</div>
					</div> 
					{% endif %}

					<form action="market_info?id={{ client.pk }}" method="POST" id="edit-form"> {% csrf_token %}
						<!-- Contact information -->
						<h3>Información de contacto</h3>
						<table class="table table-hover">
							<tr>
								<td class="col-xs-4">Nombre</td>
								<td class="col-xs-8 read">{{ client }}</td>
								<td class="write">
									<span class="col-xs-6">{{ client_form.first_name }}</span>
									<span class="col-xs-6">{{ client_form.last_name }}</span>
								</td>
							</tr>
							<tr>
								<td>Rut</td>
								<td class="read">{{ client.rut }}</td>
								<td class="write">{{ client_form.rut }}</td>
							</tr>
							<tr>
								<td>Número</td>
								<td class="read"><a href="tel:{{ client.contact_number_1 }}">{{ client.contact_number_1 }}</a></td>
								<td class="write">{{ client_form.contact_number_1 }}</td>
							</tr>
							<tr id="number-2" style="{% if not client.contact_number_2 %}display: none;{% endif %}">
								<td>Número 2</td>
								<td class="read"><a href="tel:{{ client.contact_number_2 }}">{{ client.contact_number_2 }}</a></td>
								<td class="write">{{ client_form.contact_number_2 }}</td>
							</tr>
							<tr>
								<td>Email</td>
								<td class="read"><a href="mailto:{{ client.email }}">{{ client.email }}</a></td>
								<td class="write">{{ client_form.email }}</td>
							</tr>
						</table>

						<!-- Company information  -->
						<h3>Información de compañía</h3>
						<table class="table table-hover">
						{% if client.company %}
							<tr>
								<td class="col-xs-4">Compañía</td>
								<td class="col-xs-8"><a href="market_company?id={{ client.company.pk }}">{{ client.company }}</a></td>
							</tr>
							<tr>
								<td>Rut compañía</td>
								<td id="rut">{{ client.company.rut }}</td>
							</tr>
							<tr>
								<td>Cargo</td>
								<td class="read">{{ client.position }}</td>
								<td class="write">{{ client_form.position }}</td>
							</tr>
						{% else %}
							<tr><td>Persona natural</td></tr>
						{% endif %}
						</table>

						{% if client.type_of_client.type == "Actual" %}
						<!-- Comercial information -->
						<h3>Información comercial</h3>
						<table class="table table-hover">
							<tr>
								<td class="col-xs-4">Tamaño</td>
								<td class="col-xs-8">{{ size }}</td>
							</tr>
							<tr>
								<td>Número de compras</td>
								<td>{{ n }}</td>
							</tr>
							<tr>
								<td>Precio/kg promedio</td>
								<td>$ {{ avg_price }}</td>
							</tr>
							<tr>
								<td>Volumen promedio</td>
								<td>{{ avg_volume }} [kg]</td>
							</tr>
							<tr>
								<td>Variedades</td>
								<td>{% for key, values in varieties.items %}
										{{ key }}
										({{ values }}%), 
									{% endfor %}
								</td>
							</tr>
						</table>
						<a href="add_sale?id={{ client.id }}" class="btn btn-primary" id="register-sale">Registrar transacción</a>
						<a href="sales_history?id={{ client.id }}" class="btn btn-default" id="view-historic-transatcions">Ver historial</a>
						<p class="pull-right">Información referente a los últimos 3 años.</p>
						{% endif %}

						<!-- Geographical information -->
						<h3>Información geográfica</h3>
						<table class="table table-hover">
							<tr>
								<td class="col-xs-4">Región</td>
								<td class="col-xs-8 read">{{ geo_info.region }}</td>
								<td class="write">{{ geographical_form.region }}</td>
							</tr>
							<tr>
								<td>Provincia</td>
								<td class="read">{{ geo_info.province }}</td>
								<td class="write">
									<select name="province" id="id_province" class="form-control input-sm">
										<option selected="selected" value="">Seleccione provincia</option>
									</select>
									<input type="hidden" id="province_trick" name="province_trick" value="">
								</td>
							</tr>
							<tr>
								<td>Comuna</td>
								<td class="read">{{ geo_info.commune }}</td>
								<td class="write">
									<select name="commune" id="id_commune" class="form-control input-sm">
										<option selected="selected" value="">Seleccione comuna</option>
									</select>
								</td>
							</tr>
							<tr>
								<td>Dirección</td>
								<td class="read">{{ geo_info.address }}</td>
								<td class="write">{{ geographical_form.address }}</td>
							</tr>
						</table>
						<div class="col-bg-12" id="map-canvas" style="display: none;"><!-- map goes here --></div><br>
						<button type="button" class="btn btn-default" id="mapButton" onclick="displayMap();">Mostrar mapa</button>

						<!-- Observations -->
						<h3>Observaciones</h3>
						<div class="read" style="border: 1px solid #CCCCCC">
							<p id="observations" class="text-justify" style="margin: 1%; white-space: pre-wrap">{{ client.observations }}</p>
						</div>
						<div class="write" style="display: none;">
							{{ client_form.observations }}
						</div>
						<br><button type="submit" form="edit-form" class="btn btn-primary save-changes" style="display: none;">Guardar</button>
						{% if client.type_of_client.type == "Potencial" %}
							<button name="upgrade" type="submit" class="btn btn-warning write" style="display: none;" onclick="return confirm('Está seguro que desea convertir a {{ client }} en Cliente Actual?');">Transformar en cliente actual</button>
						{% endif %}
						<button name="delete" class="btn btn-danger pull-right write" style="display: none;" onclick="return confirm('Está seguro que desea eliminar a {{ client }} de la base de datos?\nEste proceso es irreversible.');">Borrar</button>
					</form>
				</div>

			</div>
			<hr>{% include "menu_toggle.html" %}
			<a href="market_table{% if client.type_of_client.type == 'Potencial' %}_potential{% endif %}" class="btn btn-default" id="return">Volver</a>
		</div>

	</div>

	<script type="text/javascript">
	$(document).ready(function(){
		$("#id_first_name").val("{{ client.first_name }}");
		$("#id_last_name").val("{{ client.last_name }}");
		$("#id_rut").val("{{ client.rut }}");
		$("#id_contact_number_1").val({{ client.contact_number_1 }});
		$("#id_contact_number_2").val({{ client.contact_number_2 }});
		$("#id_email").val("{{ client.email }}");
		$("#id_position").val("{{ client.position }}");
		$("#id_observations").val( $("#observations").text() );

		$("#id_region")[0].selectedIndex = {{ geo_info.region.pk }};
		if ("{{ geo_info.province }}" != "None"){
			var provinceSelector = document.getElementById("id_province");
			provinceSelector.options[0] = new Option('{{ geo_info.province }}', '{{ geo_info.province.pk }}');
			$("#province_trick").val("{{ geo_info.province }}");
		}
		if ("{{ geo_info.commune }}" != "None"){
			var communeSelector = document.getElementById("id_commune");
			communeSelector.options[0] = new Option('{{ geo_info.commune }}', '{{ geo_info.commune }}');
		}
		$("#id_address").val("{{ geo_info.address }}");
	});

	$("#edit-button").click(function (){
		$(".save-changes").slideToggle("fast");
		$("#number-2").show();
		$(".read").toggle();
		$(".write").toggle(100);
	});
	</script>

</body>
</html>

crops_and_markets_app/templates/markets/market_table.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="crops and markets, and bkupfer's thesis">
	<meta name="keywords" content="semillas sz, crops and markerts, bkupfer">
	<meta name="author" content="bkupfer">
	<link rel="shortcut icon" href="static/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="static/img/favicon.ico" type="image/x-icon">

	<title>Crops and Markets</title>

	<!-- Bootstrap Core CSS -->
	<link href="static/css/bootstrap.min.css" rel="stylesheet">
	<link href="static/css/simple-sidebar.css" rel="stylesheet">

	<style type="text/css">
	input {
		border:solid 1px #ccc;
		border-radius: 5px;
		padding:7px 14px;
		margin-bottom:10px
	}
	input:focus {
		border-color:#aaa;
	}
	</style>

	<script src="static/js/jquery.js"></script>
	<script async src="static/js/bootstrap.min.js"></script>
	<script async src="static/js/menu_toggle.js"></script>
	<script async src="static/js/googleanalytics.js"></script>

	<!-- Data tables -->
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
	<script defer src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
	<!--<link href="static/css/jquery.dataTables.min.css" rel="stylesheet">
		<script src="static/js/jquery.dataTables.min.js"></script>
	-->

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>

	<div id="wrapper">

		{% include "sidebar.html" %}

		<div id="page-content-wrapper">
			<div class="container-fluid">
				<h2>Tabla de {% if potential_table %} potenciales {% endif %}clientes</h2>
				
				{% if messages %}
				<!-- For message to user -->
				<div class="row">
					<div class="col-xs-12">
					{% for message in messages %}
						<p class="alert alert-{% if message.tags == 'success' %}success{% else %}danger{% endif %} text-center">
							{{ message }}
						</p>
					{% endfor %}
					</div>
				</div> 
				{% endif %}

				<table id="clients-table" class="display" cellspacing="0" width="100%">
					<thead>
						<tr>
							<th>Cliente</th>
							<th>Compañía</th>
							<th>Región</th>
							<th>Provincia</th>
							{% if not potential_table %}<th>Tamaño</th>{% endif %}
						</tr>
					</thead>
					<tbody>
						{% for client in clients %}
						<tr>
							<td><a href="market_info?id={{ client.pk }}">{{ client }}</a></td>
							<td>
								{% if client.company %}
									<a href="market_company?id={{ client.company.pk }}">{{ client.company }}</a>
								{% else %}
									<abbr title="Persona Natural">P.N.</abbr>
								{% endif %}
							</td>
							<td>
								{% for gm in client.geomarker_set.all %}
									{{ gm.region }} 
								{% endfor %}
							</td>
							<td>
								{% for gm in client.geomarker_set.all %}
									{{ gm.province }} 
								{% endfor %}
							</td>
							{% if not potential_table %}
								<td>{% if client.size == "0" %}
										<abbr title="No hay ventas registradas">N.V.</abbr>
									{% else %}
										{{ client.size }}
									{% endif %}
								</td>
							{% endif %}
						</tr>
						{% empty %}
						<tr>
							<td>No hay clientes en la base de datos.</td>
							<td></td><td><td></td></td>{% if not potential_table %}<td></td>{% endif %}
						</tr>
						{% endfor %}
					</tbody>
				</table>
				{% if not potential_table %}<p class="pull-right">Información de tamaño referente a los últimos 3 años.</p>{% endif %}		
			</div>
			<hr>{% include "menu_toggle.html" %}
		</div>
	</div>

	<script>
	$(document).ready(function(){
		$('#clients-table').DataTable({
			 "language": {
			 	"url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
			}
		});
	});
	</script>

</body>

<script>
	$("#markets_table{% if potential_table %}_potential{% endif %}").addClass("active");
</script>

</html>